### ISSUE TITLE
Restore spies automatically?

### ISSUE THREAD

**Issue by strathmeyer** [jasmine-sinon/jasmine-sinon#1]
One of the best parts about sinon-qunit.js is that it proxies Qunit.test() through sinon.test() so that any spies/mocks/etc are automatically restored after the test.
- http://sinonjs.org/docs/api/#sinon-test
- http://sinonjs.org/releases/sinon-qunit-1.0.0.js

I haven't looked at the internals of Jasmine, but do you think it would be possible to do something similar?  I'm willing to help write it!

**Comment by froots** [comment]
I see no reason why you couldn't do this, although it wasn't my original intention when writing the code. I've always been happy enough with using sinon.test to wrap the Jasmine spec functions if needed, but I do like the seamless integration so you don't have to remember to do this.

Feel free to fork and get a working example, or even better, submit a pull request (with specs if possible).

**Comment by strathmeyer** [comment]
Cool. I'll take a look and see what I can come up with.

**Comment by moll** [comment]
Any news on this?

I'd imagine running through a bunch of it blocks while using Sinon we'll end up with respying quite a lot of stuff.

**Comment by strathmeyer** [comment]
Doh. Not since April.  :-\  Try this: https://github.com/froots/jasmine-sinon/pull/2

I apologize for not having tested it myself.

**Comment by strathmeyer** [comment]
continue in https://github.com/froots/jasmine-sinon/issues/2 which includes the pull request

**Comment by moll** [comment]
I'd suggest discussion in this issue is a better and more centralized place than individual pull requests. :)

Anyway, we should also patch beforeEach and such, because before blocks make a good place where to generate common mocks/spies.

The solution I came up with myself is:

```
beforeEach(function() {
    window.sin = sinon.sandbox.create(
        sinon.getConfig({injectInto: this, useFakeServer: false})
    );
});
afterEach(function() {
    window.sin.restore();
});
```

Positive side of it is no need to patch methods and it works from beforeEach.

**Comment by moll** [comment]
I tried saving a sandbox to window.sinon (saving the previous value of sinon, of course), but that didn't work well with the way sinon is written and calls itself. That would've been a transparent way to clean up after sinon.
