### ISSUE TITLE
Spying on existing methods does not work

### ISSUE THREAD

**Issue by mariusGundersen** [jasmine-sinon/jasmine-sinon#15]
sinon lets you spy on an existing method using the following syntax (from the sinonjs.org documentation):

``` js
sinon.spy(jQuery, "ajax");
```

unfortunately this does not work with jasmine-sinon. In the following test case I expect the test to complete successfully, but instead I get the result `Error: Expected a spy, but got Function`. Is the matcher a bit too clever? Is there a better way to decide if something is a spy, so this kind of syntax can work?

``` js

    describe("when spying on an existing object", function () {

        beforeEach(function () {

            this.object = {
                doSomething: function() {
                }
            };

            sinon.spy(this.object, 'doSomething');

            this.object.doSomething();
        });


        it("Should be a spy", function () {
            expect(this.object.doSomething).toHaveBeenCalled();
        });
    });
```

**Comment by froots** [comment]
I can't replicate this error using my set up of Karma on Chrome, Chrome Canary, Firefox or Phantom JS.

What environment, browser and test runner are you using? 

I haven't yet tested against Jasmine 2.0 either, so you're likely to have problems with that.

**Comment by mariusGundersen** [comment]
Sorry, yeah, it seems it works after all
