### ISSUE TITLE
1 error on Jasmine 2.0.0rc5

### ISSUE THREAD

**Issue by tommeier** [jasmine-sinon/jasmine-sinon#18]
![screen shot 2013-11-13 at 12 52 02 am](https://f.cloud.github.com/assets/19973/1522082/b1c92f56-4ba1-11e3-9b6f-d23a24fffb16.png)
![screen shot 2013-11-13 at 12 51 56 am](https://f.cloud.github.com/assets/19973/1522083/b398f0aa-4ba1-11e3-8a08-87cb5339c6d3.png)

```
Uncaught TypeError: Cannot read property 'prototype' of undefined 
```

(Jasmine.Matchers do not exist anymore)

**Comment by stoodder** [comment]
Hey guys, I messed around with the jasmine-sinon.js source and created a work around solution:

https://gist.github.com/stoodder/8749102

This is derived from the original jasmine-sinon except that is uses the new pieces of jasmine 2.0.0. Take it for what it is, it should work the same as the previous one but I haven't tested yet.

Also, I apologize for the weird JS, this is compiled CoffeeScript.

**Comment by shakerlxxv** [comment]
@stoodder, thanks! Your changes are working for me as a quick upgrade.

**Comment by stoodder** [comment]
@shakerlxxv No problem!

**Comment by kentandersen** [comment]
Any thoughts on getting this into the main repo? @stoodder's gist work atm, however I would like to see this as part of the froots/jasmine-sinon repo (or a fork)

**Comment by froots** [comment]
I'm going to start work on this, but release may have to wait on [jasmine-node](https://github.com/jasmine-contrib/grunt-jasmine-node/pull/41) support for Jasmine 2.0, which looks to be close.

I'll look at what @stoodder has done. If you've got any other feature requests other than plain compatibility with 2.0, be sure to add an issue.

**Comment by froots** [comment]
There is now a version passing the existing browser unit tests on the [jasmine-2](https://github.com/froots/jasmine-sinon/tree/jasmine-2) branch. My plan is to release this as 0.4 after some more testing and amendments and keep 0.3 for Jasmine 1.x.

**Comment by froots** [comment]
Jasmine 2.0 support now in v0.4.0.
