### ISSUE TITLE
Update to jasmine 2.0 ?

### ISSUE THREAD

**Issue by Chrysweel** [jasmine-sinon/jasmine-sinon#22]
Hi!

I want update to jasmine 2.0, but jasmine-sinon has requirement : 

> jasmine-sinon#0.3.1 depend on jasmine#~1.3.1 which resolved to 1.3.1

Can I use the jasmine sinon with jasmine 2.0 ?

**Comment by hoschi** [comment]
No it doesn't work, see #18
:+1: for updating this to jasmine 2.0

**Comment by hyzhak** [comment]
:+1:

**Comment by adrianstainforth** [comment]
:+1:

**Comment by Chrysweel** [comment]
Ok thanks !
