### ISSUE TITLE
Receiving "Typeerror: cannot read property 'ToHaveBeenCalled' of undefined"

### ISSUE THREAD

**Issue by Jon-Biz** [jasmine-sinon/jasmine-sinon#28]
Just did a bower reinstall of jasmine#2.0.0, sinon#1.9.1, jasmine-sinon#0.4.0. 

Stacktrace (edited for readability)

```
TypeError: Cannot read property 'toHaveBeenCalled' of undefined
        at createMatcher (/jasmine-sinon/lib/jasmine-sinon.js:168:36)
        at createJasmineSinonMatchers /jasmine-sinon/lib/jasmine-sinon.js:209:51)
        at null.<anonymous> (/jasmine-sinon/lib/jasmine-sinon.js:215:25)
```

Thanks!

**Comment by froots** [comment]
Can you give me a bit more information about your test runner, spec code, etc.?

**Comment by Jon-Biz** [comment]
Sorry - it was a problem with sinonjs compatiblity and loading. Jasmine-sinon is working now.

**Comment by krawaller** [comment]
For others who walked into the same trap (like me); this problem is caused when we fail to heed what the readme says about Jasmine 1.x / 2.x compatibility.
