### ISSUE TITLE
Why use the past perfect tense in the passive voice?

### ISSUE THREAD

**Issue by andrewdeandrade** [jasmine-sinon/jasmine-sinon#3]
Out of curiosity, why did you opt for matchers that use the past perfect tense in the passive voice instead of simply the present tense in the passive voice? I ask because both convey pretty much the same meaning, but the present tense is easier to read and reason about. It also requires less typing to boot.

e.g.

`expect(mySpy).toBeCalledOnce()` vs. `expect(mySpy).toHaveBeenCalledOnce();`

`expect(mySpy).toBeCalledWith(1)` vs. `expect(mySpy).toHaveBeenCalledWith(1);`

**Comment by froots** [comment]
2 reasons:
1. The Jasmine matchers already used the past perfect tense, so I was just following from that
2. Using the present tense implies that the expected behaviour could be yet to occur, which would be more like a mock.
