### ISSUE TITLE
Sinon.js and Rhino issue with Fake Timers

### ISSUE THREAD

**Issue by mklymyshyn** [jasmine-sinon/jasmine-sinon#6]
This is continuation of my blog post about Sinon.js and Fake timers: [Headless JavaScript testing, Sinon.js, Fake Timers and Rhino](http://djangoandother.blogspot.com/2012/02/headless-javascript-testing-sinonjs.html).

As promised, I've made environment with Rhino and Sinon.js where test for Fake Timers is not work properly ([download](http://dl.dropbox.com/u/28023777/sinon-rhino.tar.bz2)). To execute tests use `./runtests.sh`, you need to have Java.

I found debugger for Rhino and I will try to solve this issue but I don't have enough experience to do it efficiently.

Here is output:

```
Maxs-MacBook-Air:Sinon-Rhino maxk$ ./runtests.sh 
[  Envjs/1.6 (Rhino; U; Mac OS X x86_64 10.7.3; en-US; rv:1.7.0.rc2) Resig/20070309 PilotFish/1.2.13  ]
Loading: runner.html
Runner Started.
Timers Issue Test : Failing timer test ... 
Failed.
Timers Issue Test: 1 of 4 passed.
Runner Finished.
1 spec, 1 failure in 0.092s.
```

**Comment by froots** [comment]
@joymax Did you mean to post this on the sinonjs repo? I'm not sure what relevance this has to jasmine-sinon. Closing.

**Comment by mklymyshyn** [comment]
Sorry, you're right, wrong tab. Thanks.
