### ISSUE TITLE
package.json to allow jasmine-sinon to be used with npm

### ISSUE THREAD

**Issue by devgeeks** [jasmine-sinon/jasmine-sinon#9]
Is there any chance of a `package.json` file so that jasmine-sinon can be added as a dev dependency using `npm` ?

**Comment by xiaods** [comment]
interesting. +1

**Comment by devgeeks** [comment]
I only ask because I am using a Grunt Jasmine runner and Sinon via `npm` running headless tests with PhantomJS. It is then using continuous integration by Travis-CI. 

So I really need to automate my dependencies as much as possible.

**Comment by froots** [comment]
@devgeeks How are you including sinon.js in your Gruntfile? I'd appreciate a code sample. Sorry for the delay in getting to this.

**Comment by devgeeks** [comment]
We have actually moved on to Mocha (for internal reasons), but we were using npm to install sinon as a dependancy, then using Grunt to run the tests using the Grunt Jasmine runner plugin (https://github.com/jasmine-contrib/grunt-jasmine-runner).

Our problem came when we wanted to automate the inclusion of your project as we could not add it using npm, the only option was something like bower, but that would pollute our non-test environment.
